version: '3.4'

services:
  # postgresql database
  postgres:
    restart: always
    image: postgres:12.14-alpine
    ports:
      - 5432
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    volumes:
      - pgsql_data:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d/
    networks:
      - net
  # postgresql pgadmin
  pgadmin:
    restart: always
    image: dpage/pgadmin4:6
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "4040:80"
      - "40401:443"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - net
  # proxy microservice
  proxy_microservice:
    restart: always
    build:
      context: proxy_microservice
    environment:
      USER_MICROSERVICE_HTTP_SCHEME: http
      USER_MICROSERVICE_HOST: user_microservice
      AUTH_MICROSERVICE_HTTP_SCHEME: http
      AUTH_MICROSERVICE_HOST: auth_microservice
      SERVICE_PORT: ${SERVICE_PORT}
    ports:
      - 8000:80
    depends_on:
      - postgres
      - user_microservice
      - auth_microservice
    networks:
      - net
  # authentication microservice
  auth_microservice:
    restart: always
    build:
      context: auth_microservice
    environment:
      APP_DB_USERNAME: ${POSTGRES_USERNAME}
      APP_DB_PASSWORD: ${POSTGRES_PASSWORD}
      APP_DB_NAME: ${POSTGRES_DATABASE}
      APP_DB_HOST: postgres
      SERVICE_PORT: ${SERVICE_PORT}
    depends_on:
      - postgres
    networks:
      - net
  # user microservice
  user_microservice:
    restart: always
    build:
      context: user_microservice
    environment:
      APP_DB_USERNAME: ${POSTGRES_USERNAME}
      APP_DB_PASSWORD: ${POSTGRES_PASSWORD}
      APP_DB_NAME: ${POSTGRES_DATABASE}
      APP_DB_HOST: postgres
      SERVICE_PORT: ${SERVICE_PORT}
    depends_on:
      - postgres
      - auth_microservice
    networks:
      - net

volumes:
  pgsql_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  net:
    driver: bridge
